// Server-side access to everything under data/protocol, which is generated by
// scripts/sync-protocol.mjs and scripts/snapshot-chain.mjs. Pages read the
// protocol through this module so that no address, fee, or threshold is ever
// written into a page by hand.

import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import type { Abi, AbiEvent, AbiFunction } from "viem"
import { formatUnits, toEventSelector, toFunctionSelector, toFunctionSignature } from "viem"

const protocolDir = join(process.cwd(), "data", "protocol")

const readJson = <T>(...segments: string[]): T =>
  JSON.parse(readFileSync(join(protocolDir, ...segments), "utf8")) as T

const readJsonIfPresent = <T>(...segments: string[]): T | null => {
  const path = join(protocolDir, ...segments)
  return existsSync(path) ? (JSON.parse(readFileSync(path, "utf8")) as T) : null
}

export type ContractMeta = {
  name: string
  source: string
  license: string | null
  pragma: string | null
  compiler: string | null
  functions: number
  events: number
}

export type ProtocolMeta = {
  syncedAt: string
  protocolRepo: string
  protocolCommit: string | null
  appRepo: string
  appCommit: string | null
  contracts: ContractMeta[]
  tests: {
    total: number
    invariants: number
    byFile: { file: string; tests: number; invariants: number }[]
  }
  deployedNetworks: string[]
}

export type Network = {
  key: string
  label: string
  /** The chain's own name, as the application defines it. */
  name: string
  testnet: boolean
  foundryProfile: string
  chainId: number
  rpcUrl: string
  explorer: { name: string | null; url: string }
}

export type Limits = {
  bps: number
  pPrecision: string
  scaleFactor: string
  defaults: {
    originationFeeBps: number
    redemptionFeeBps: number
    liquidationIncentiveBps: number
  }
  maxOriginationFeeBps: number
  maxRedemptionFeeBps: number
  maxLiquidationIncentiveBps: number
  maxPriceFeedDecimals: number
  passport: { fullMask: number; checks: number }
}

export type Revert = { scope: string | null; message: string }

export type Deployment = {
  network: string
  chainId: number
  deployBlock: number | null
  deployedAt: string | null
  commit: string | null
  contracts: Record<string, string>
  tokens: Record<string, string>
  source: string
}

export type AssetState = {
  address: string
  symbol: string | null
  name: string | null
  decimals: number | null
  enabled: boolean
  maxLtvBps: number
  liqThresholdBps: number
  storedPriceUsd1e18: string
  priceFeed: string | null
  priceFeedDecimals: number | null
  priceSource: "chainlink" | "manual"
  feedDescription: string | null
  currentPriceUsd1e18: string | null
  priceUpdatedAt: number | null
  /** The asset's own price guard. Null on a pool too old to have one. */
  maxPriceAgeSeconds: number | null
  maxDeviationBps: number | null
  minPriceUsd1e18: string | null
  maxPriceUsd1e18: string | null
}

export type ChainSnapshot = {
  network: string
  chainId: number
  readAt: string
  blockNumber: number
  blockTimestamp: number
  pool: {
    address: string
    owner: string
    priceUpdater: string | null
    passportRegistry: string | null
    passportGate: boolean
    stable: { address: string; symbol: string | null; name: string | null; decimals: number | null }
    originationFeeBps: number
    redemptionFeeBps: number
    liquidationIncentiveBps: number
    totalDeposits: string
    availableLiquidity: string
    protocolFees: string
    productP: string
    currentScale: number
    assets: AssetState[]
  }
  registry: { address: string; owner: string | null; fullMask: number } | null
  desk: {
    address: string
    owner: string | null
    auditor: string | null
    partnershipCount: number
  } | null
}

export const protocolMeta = (): ProtocolMeta => readJson<ProtocolMeta>("meta.json")
export const networks = (): Network[] => readJson<Network[]>("networks.json")
export const limits = (): Limits => readJson<Limits>("limits.json")

export const deploymentOf = (network: string): Deployment | null =>
  readJsonIfPresent<Deployment>("deployments", `${network}.json`)

export const snapshotOf = (network: string): ChainSnapshot | null =>
  readJsonIfPresent<ChainSnapshot>("onchain", `${network}.json`)

export const abiOf = (contract: string): Abi => readJson<Abi>("abi", `${contract}.json`)

export type RiskDisclosure = {
  source: string
  lead: string | null
  items: { title: string; body: string }[]
  closing: string
}

export const riskDisclosure = (): RiskDisclosure => readJson<RiskDisclosure>("risk-disclosure.json")

export type KeeperReference = {
  scripts: Record<string, string>
  dependencies: Record<string, string>
  configFields: string[]
  configExample: Record<string, unknown>
  abi: string[]
  defaultIntervalMs: number
}

export const keeperReference = (): KeeperReference => readJson<KeeperReference>("keeper.json")

export const revertsOf = (contract: string): Revert[] =>
  readJson<Record<string, Revert[]>>("reverts.json")[contract] ?? []

/** Every network paired with whatever has been deployed and read on it. */
export type NetworkState = {
  network: Network
  deployment: Deployment | null
  snapshot: ChainSnapshot | null
}

export const networkStates = (): NetworkState[] =>
  networks().map(network => ({
    network,
    deployment: deploymentOf(network.key),
    snapshot: snapshotOf(network.key)
  }))

// --- ABI derived reference -------------------------------------------------

export type EventReference = {
  name: string
  signature: string
  topic0: string
  indexed: string[]
  data: string[]
}

export const eventsOf = (contract: string): EventReference[] =>
  (abiOf(contract).filter(item => item.type === "event") as AbiEvent[]).map(event => ({
    name: event.name,
    signature: `${event.name}(${event.inputs.map(input => input.type).join(",")})`,
    topic0: toEventSelector(event),
    indexed: event.inputs.filter(input => input.indexed).map(input => `${input.type} ${input.name}`),
    data: event.inputs.filter(input => !input.indexed).map(input => `${input.type} ${input.name}`)
  }))

export type FunctionReference = {
  name: string
  signature: string
  selector: string
  stateMutability: string
  inputs: string[]
  outputs: string[]
}

const functionsOf = (contract: string): AbiFunction[] =>
  abiOf(contract).filter(item => item.type === "function") as AbiFunction[]

const describe = (fn: AbiFunction): FunctionReference => ({
  name: fn.name,
  signature: toFunctionSignature(fn),
  selector: toFunctionSelector(fn),
  stateMutability: fn.stateMutability,
  inputs: fn.inputs.map(input => `${input.type}${input.name ? ` ${input.name}` : ""}`),
  outputs: (fn.outputs ?? []).map(output => `${output.type}${output.name ? ` ${output.name}` : ""}`)
})

/** The named functions of a contract, in the order asked for, resolved from the ABI. */
export const functionReference = (contract: string, names: string[]): FunctionReference[] => {
  const all = functionsOf(contract)
  return names.map(name => {
    const fn = all.find(candidate => candidate.name === name)
    if (!fn) throw new Error(`${contract} has no function ${name}; regenerate data/protocol`)
    return describe(fn)
  })
}

// --- formatting ------------------------------------------------------------

export const formatBps = (bps: number) => {
  const percent = bps / 100
  return `${Number.isInteger(percent) ? percent : percent.toFixed(2)}%`
}

/** Prices are carried as USD with 18 decimals throughout the pool. */
export const formatUsd1e18 = (value: string | null) => {
  if (value === null) return null
  const asNumber = Number(formatUnits(BigInt(value), 18))
  return asNumber.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 })
}

export const formatToken = (value: string, decimals: number | null, symbol?: string | null) => {
  const amount = Number(formatUnits(BigInt(value), decimals ?? 18))
  const rendered = amount.toLocaleString("en-US", { maximumFractionDigits: 2 })
  return symbol ? `${rendered} ${symbol}` : rendered
}

export const formatDuration = (seconds: number) => {
  if (seconds === 0) return "disabled"
  if (seconds % 3600 === 0) return `${seconds / 3600}h`
  if (seconds % 60 === 0) return `${seconds / 60}m`
  return `${seconds}s`
}

export const explorerAddressUrl = (network: Network, address: string) =>
  `${network.explorer.url}/address/${address}`

export const shortCommit = (commit: string | null) => (commit ? commit.slice(0, 10) : null)
